default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:


development:
  <<: *default
#  database: appmakerstore_development
#  database: appsmakerstore_demo
  database: appsmakerstore


test:
  database: ams_travis_test5

production:
  database: appsmakerstore

